name: safe_area
description: Diploma project for AMCP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0
  dio: ^4.0.4
  flutter_native_splash: ^1.3.2
  provider: ^6.0.1
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  connectivity_plus: ^2.2.0
  location: ^4.3.0
  geolocator: ^8.0.3
  syncfusion_flutter_maps: ^19.4.43-beta
  geojson: ^1.0.0
  geopoint: ^1.0.0
  geojson_vi: ^2.0.6
  flutter_map: ^0.14.0
  ## Для экспериментов с сохранением данных
  hive: ^2.0.6
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.0
  google_fonts: ^2.1.0
  build_runner: ^2.1.4
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/maps/australia.json
